name: Translations Sync

on:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types:
      - transifex

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update translations
        uses: liri-infra/translation-action@master
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        with:
          ssh_key: ${{ secrets.CI_SSH_KEY }}
          committer_name: Liri CI
          committer_email: ci@liri.io
          translations_folder: translations
